api/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from . import views

urlpatterns = [

    url(r'^role/nextlayer$', 'api.services.GetRoleNextLayer', name="api_rolenextlayer"),
    url(r'^getgameproj$', 'api.opensv.GetGameProject', name="api_getgameproj"),
    url(r'^getgameinfo$', 'api.opensv.GetGameInfo', name="api_getgameinfo"),

    url(r'^getmergegameinfo$', 'api.mergesv.GetMergeGameInfo', name="api_getmergegameinfo"),

    url(r'^addserverinfo$', 'api.opensv.ServerInfomationCreateApi', name="api_addserverinfo"),
    url(r'^setserverstatus$', 'api.opensv.ServerInfomationStatusApi', name="api_setserverstatus"),

    url(r'^opensv/settaskstatus$', 'api.opensv.SetServerTaskStatusApi', name="api_settaskstatus"),
    url(r'^mergesv/settaskstatus$', 'api.mergesv.SetServerTaskStatusApi', name="api_settaskstatus"),

    url(r'^getserverstatuslist$', 'api.opensv.GetServerStatusListApi', name="api_getserverstatuslist"),

    url(r'^creategame/(.+)/$', 'api.opensv.RunCreateGameApi', name="api_creategame"),
    url(r'^mergegame/(.+)/$', 'api.mergesv.RunMergeGameApi', name="api_mergegame"),

]

conf/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from  userinfo.views import login_view, logout_view, logged_view, index_view
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
urlpatterns = [
    # Examples:
    # url(r'^$', 'keeper.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', (login_required(index_view)), name='index'),
    url(r'^accounts/login/$', login_view, name='login'),
    url(r'^accounts/logout/$', logout_view, name='login_out'),
    url(r'^user/logged$', logged_view),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^userinfo/', include('userinfo.urls', namespace='userinfo')),
    url(r'^openserver/', include('openserver.urls', namespace='openserver')),
    url(r'^mergerserver/', include('mergerserver.urls', namespace='mergerserver')),
    url(r'^api/', include('api.urls', namespace='api')),

]

mergerserver/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from . import views

urlpatterns = [


    # url(r'^$', cache_page(60 * 60)(login_required(index_view)), name='index'),

    url(r'^opt$', login_required(views.MergerServerView.as_view()), name='opt'),
    url(r'^mergesvtask/list$', (login_required(views.MergerServerTaskList.as_view())), name='mergeservertask_list'),
    url(r'^mergesvtask/detail/(?P<pk>[\w-]+)$', login_required(views.MergerServerTaskDetail.as_view()), name='mergeservertask_detail'),


    # url(r'^hostgroupconfig/add$', login_required(views.HostGroupConfigCreate.as_view()), name='hostgroupconf_create'),
    # url(r'^hostgroupconfig/list$', (login_required(views.HostGroupConfigList.as_view())), name='hostgroupconf_list'),
    # url(r'^hostgroupconfig/edit/(?P<pk>[\w-]+)$', login_required(views.HostGroupConfigUpdate.as_view()), name='hostgroupconf_update'),
    # url(r'^hostgroupconfig/detail/(?P<pk>[\w-]+)$', login_required(views.HostGroupConfigDetail.as_view()), name='hostgroupconf_detail'),
    # url(r'^hostgroupconfig/del/(?P<pk>[\w-]+)$', login_required(views.HostGroupConfigDelete.as_view()), name='hostgroupconf_delete'),

    # url(r'^hostproj/add$', login_required(views.GameProjectCreate.as_view()), name='gameproj_create'),
    # url(r'^hostproj/list$', (login_required(views.GameProjectList.as_view())), name='gameproj_list'),
    # url(r'^hostproj/edit/(?P<pk>[\w-]+)$', login_required(views.GameProjectUpdate.as_view()), name='gameproj_update'),
    # url(r'^hostproj/detail/(?P<pk>[\w-]+)$', login_required(views.GameProjectDetail.as_view()), name='gameproj_detail'),
    #

    #
    # url(r'^serverinfo/list$', (login_required(views.ServerInfomationList.as_view())), name='serverinfo_list'),
    # url(r'^serverinfo/detail/(?P<pk>[\w-]+)$', login_required(views.ServerInfomationDetail.as_view()), name='serverinfo_detail'),



]

openserver/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from . import views

urlpatterns = [


    # url(r'^$', cache_page(60 * 60)(login_required(index_view)), name='index'),

    url(r'^opt$', login_required(views.openServerView.as_view()), name='opt'),

    # url(r'^hostgroupconfig/add$', login_required(views.HostGroupConfigCreate.as_view()), name='hostgroupconf_create'),
    # url(r'^hostgroupconfig/list$', (login_required(views.HostGroupConfigList.as_view())), name='hostgroupconf_list'),
    # url(r'^hostgroupconfig/edit/(?P<pk>[\w-]+)$', login_required(views.HostGroupConfigUpdate.as_view()), name='hostgroupconf_update'),
    # url(r'^hostgroupconfig/detail/(?P<pk>[\w-]+)$', login_required(views.HostGroupConfigDetail.as_view()), name='hostgroupconf_detail'),
    # url(r'^hostgroupconfig/del/(?P<pk>[\w-]+)$', login_required(views.HostGroupConfigDelete.as_view()), name='hostgroupconf_delete'),

    url(r'^hostproj/add$', login_required(views.GameProjectCreate.as_view()), name='gameproj_create'),
    url(r'^hostproj/list$', (login_required(views.GameProjectList.as_view())), name='gameproj_list'),
    url(r'^hostproj/edit/(?P<pk>[\w-]+)$', login_required(views.GameProjectUpdate.as_view()), name='gameproj_update'),
    url(r'^hostproj/detail/(?P<pk>[\w-]+)$', login_required(views.GameProjectDetail.as_view()), name='gameproj_detail'),

    url(r'^opensvtask/list$', (login_required(views.OpenServerTaskList.as_view())), name='openservertask_list'),
    url(r'^opensvtask/detail/(?P<pk>[\w-]+)$', login_required(views.OpenServerTaskDetail.as_view()), name='openservertask_detail'),

    url(r'^serverinfo/list$', (login_required(views.ServerInfomationList.as_view())), name='serverinfo_list'),
    url(r'^serverinfo/detail/(?P<pk>[\w-]+)$', login_required(views.ServerInfomationDetail.as_view()), name='serverinfo_detail'),



]

mergerserver/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse

from django.db import models
from userinfo.models import User
from openserver.models import GameProject

# Create your models here.
class MergerServerTask(models.Model):
    STATUS = (
        (1, "新提交"),
        (2, "合服中"),
        (3, "失败"),
        (4, "完成"),
        (5, "警告"),
    )


    description = models.CharField(max_length=200, verbose_name="合服描述")
    operator = models.ForeignKey(User, verbose_name="操作人")
    gameproject = models.ForeignKey(GameProject,verbose_name="游戏项目")
    operatetime = models.DateTimeField(auto_now=True, verbose_name="创建时间")
    status = models.IntegerField(choices=STATUS, default=1, verbose_name="任务状态")
    execoutput = models.TextField(verbose_name="执行日志")

    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('mergerserver:mergerservertask_detail', kwargs={'pk': self.pk})

class MergerGroupInTask(models.Model):
    task = models.ForeignKey(MergerServerTask, verbose_name="合服任务单")
    targetid = models.CharField(max_length=255, unique=True, verbose_name="合成服名称")

mergerserver/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
import time,json
from openserver.models import GameProject
from mergerserver.models import *
from openserver.models import ServerInfomation
from django.db import transaction

# Create your views here.

class MergerServerTaskList(ListView):
    model = MergerServerTask

class MergerServerTaskDetail(DetailView):
    print "---------------------------------"
    model = MergerServerTask
    print "---------------------------------"

    def get_context_data(self, **kwargs):

        context = super(MergerServerTaskDetail, self).get_context_data(**kwargs)
        taskid = self.kwargs["pk"]
        data = []
        try:
            for i in MergerServerTask.objects.get(id=taskid).mergergroupintask_set.all():

                status = "N/A"
                info = "N/A"

                try:
                    sf = ServerInfomation.objects.get(serverid=i.targetid.split('.')[1])
                    status = sf.get_status_display
                    info = eval(sf.extra_data)['message']

                except Exception, e:
                    pass
                tmpdt = [i.targetid.split('.')[1], status, info]

                try:
                    svinfo = ServerInfomation.objects.get(serverid=i.targetid.split('.')[1])
                    if svinfo.status == 1:
                        tmpdt[1] = svinfo.status
                    else:
                        failoutput = json.loads(svinfo.extra_data)['message']
                        tmpdt[2] = failoutput
                except Exception,e:
                    print e

                data.append(tmpdt)

            context['serverinfo'] = data
        except Exception, e:
            print 'MergerServerTaskDetail ',e

        return context


class MergerServerView(TemplateView):
    template_name = 'mergerserver/mergerserver.html'

    def post(self, request):
        gameproj = request.POST.get("gameproj", "")
        mergerservers = request.POST.get("mergerservers", "")

        mergesvs = mergerservers.split(',')

        signal = False
        try:
            hp = GameProject.objects.get(codename=gameproj)

            for i in hp.owners.all():
                if i.username == request.user.username:
                    signal = True

            if self.request.user.is_superuser:
                signal = True

            if hp.manager.username == request.user.username:
                signal = True

        except:
            return HttpResponse("提交数据有误！")

        if not signal:
            return HttpResponse("你没有权限！")

        osr = mergerServerRecord(request.user.username, gameproj, mergesvs)
        if not osr.recordinfo():
            return HttpResponse("配置出现问题,请检查!")
        return HttpResponse("success")

class mergerServerRecord(object):
    def __init__(self,username, gameproject, mergerservers):
        self.username = username
        self.gameproject = gameproject
        self.mergerservers = mergerservers

        self.operatetime = time.strftime('%Y-%m-%d %X', time.localtime())

    def recordinfo(self):

        try:

            if len(self.mergerservers)==0:
                print "mergerServerRecord recordinfo error , ready for merger group is empty"
                return False

            with transaction.atomic():
                mst = MergerServerTask.objects.create(
                    description=str(self.gameproject) + " " + " " + str(self.operatetime),
                    operator=User.objects.get(username=self.username),
                    gameproject=GameProject.objects.get(codename=self.gameproject),
                    status=1,
                )
                mst.save()

                for k in self.mergerservers:
                    mgt = MergerGroupInTask.objects.create(
                        task=mst,
                        targetid=k
                    )
                    mgt.save()


        except Exception,e:
            print "mergerServerRecord recordinfo error" ,e
            return False

        return True

templates/mergerserver/mergerserver.html
{% extends "index.html" %}

{% block header %}
    <script src="/static/bootstrap/assets/js/jquery-1.10.2.js"></script>
    <link href="/static/bootstrap/bootstrap-datetimepicker/css/my_icon_for_datepicker.css" rel="stylesheet" media="screen">
    <link href="/static/bootstrap/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">

        <style>
        form input{
            width:20%;
            height:35px;
        }
        form select{
            width:10%;
            height:30px;
        }
        form label{
            font-size:16px;
        }

        </style>
{% endblock %}

{% block body %}

    <div class="header">
        <h1 class="page-header">合服</h1>
          <ol class="breadcrumb">
              <li><a href="{% url 'index' %}">首页</a></li>
              <li class="active">合服</li>
          </ol>
    </div>

    <div class="col-xs-1 col-xs-offset-10"><a  href="{% url 'mergerserver:mergeservertask_list' %}" class="btn btn-default">合服任务单</a></div>


    <div id="page-inner"><!--  PAGE-INNER -->




        <div class="panel panel-default" style="padding:13px;"><!-- PANEL-ONE -->
            <div class="panel-heading">
                <h3 class="panel-title">查找合服信息</h3>
            </div>


            <div class="panel-body">

                <div class="row">

                    <div class="col-xs-2">
                        <select id="gameproj" name="usertype" class="form-control">
                                <option value="none">选择游戏</option>

                        </select>
                    </div>

                    <div class="col-xs-2"  style="text-align:right;">

                        <div class="input-append date form_datetime">
                            <input  id="begindate" style="width:100%;border-radius: 4px;border: 1px solid #ccc;height:34px" type="text" value="从:" >
                            <span class="add-on"><i class="icon-th"></i></span>
                        </div>
                    </div>

                    <div class="col-xs-2"  style="text-align:right;">

                        <div class="input-append date form_datetime">
                            <input  id="enddate" style="width:100%;border-radius: 4px;border: 1px solid #ccc;height:34px" type="text" value="到:" >
                            <span class="add-on"><i class="icon-th"></i></span>
                        </div>
                    </div>

                    <div class="col-xs-2"  style="text-align:center;">
                            <button  class='btn btn-primary' id="searchgames" style="width:50%;border-radius: 4px;border: 1px solid #ccc;height:34px"  value="查询" >查询</button>
                    </div>


                </div>



                <table id="newserver" class="table  table-bordered table-hover">
                    <thead>
                        <tr>
                          <th>游戏名</th>
                          <th>渠道</th>
                          <th>合服区号</th>
                          <th>合服日期</th>
                          <th>合服时间</th>
                          <th>TargetGroup</th>
                          <th><input class="checkall" type="checkbox"></th>
                        </tr>
                    </thead>

                    <tbody id="gameinfo_tbody">


                    </tbody>

                </table>
                <div style="text-align:center;" id="gameinfoemptyinfo" class="alert alert-warning"><span>没有匹配任何项</span></div>



            </div>

        </div><!-- END-PANEL-ONE -->




        <button class="btn btn-primary" style="float:right;" onclick="PostSelectData()">配置新服</button>

    </div><!--  END-PAGE-INNER -->

{% endblock %}
{% block script %}

    <script type="text/javascript" src="/static/bootstrap/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
    <script type="text/javascript" src="/static/bootstrap/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.fr.js" charset="UTF-8"></script>

    <script type="text/javascript">


    $(".form_datetime").datetimepicker({
        startDate:new Date(),
        format: 'yyyy-mm-dd',
        autoclose: true,
        todayBtn: true,
        startView: 'year',
        minView:'month',
        maxView:'decade',
        language:  'zh-CN',
    });


    $(document).ready(function (){
            loadgameproject();
    })

    $("#searchgames").click(function(){
            getgameinfo($("#gameproj").val(), $("#begindate").val(), $("#enddate").val());
    })


    function loadgameproject() {
        var url = "/api/getgameproj";
        jQuery.ajax({
            type: "post",
            url: url,
            async:false,//false代表等待ajax执行完毕后才执行alert("ajax执行完毕")语句;
            success: function (msg) {
                    $("#gameproj").empty();
                    $("#gameproj").append("<option value='None'>选择游戏</option>");
                    for(var i=0;i<msg.length;i++){
                        $("#gameproj").append("<option value="+msg[i][1]+">"+msg[i][0]+"</option>");
                    }
            }
        })
    }


     function getgameinfo(proj,begindt,enddt) {
        var dateformat =  /^(\d{4})-(\d{2})-(\d{2})$/;

        if(proj == "None"){
            alert("请选择游戏.");
            return false;
        }
        if(!dateformat.test(begindt)){
            alert("开始日期格式不正确");
            return false;
        }
        if(!dateformat.test(enddt)){
            alert("结束日期格式不正确");
            return false;
        }
        var url = "/api/getmergegameinfo";
        jQuery.ajax({
            type: "post",
            url: url,
            data: {gameproj:proj,begindate:begindt,enddate:enddt},
            async:false,//false代表等待ajax执行完毕后才执行alert("ajax执行完毕")语句;
            success: function (msg) {

                if(msg.length == 0 ){
                    $("#gameinfo_tbody").empty();
                    $("#gameinfoemptyinfo").show();
                    return;
                }
                $("#gameinfo_tbody").empty();
                for(var i=0;i<msg.length;i++){
                     $("#gameinfo_tbody").append("<tr><td>" + msg[i][0] + "</td> \
                                                      <td>" + msg[i][1] + "</td> \
                                                      <td>" + msg[i][2] + "</td> \
                                                      <td>" + msg[i][3] + "</td> \
                                                      <td>" + msg[i][4] + "</td> \
                                                      <td>" + msg[i][5] + "</td> \
                                                      <td><input value='" + msg[i][6] + "." + msg[i][5] + "' class='checkchild' type='checkbox'></td> \
                                                  </tr>");
                }
                $("#gameinfoemptyinfo").hide();
            }
        })
    }


    function PostSelectData(){
        var gameproj=$("#gameproj").val();

        var newservers="";
        var items=document.getElementsByClassName("checkchild");    //获取table对像
        for(var i=0;i<items.length;i++){
            if(items[i].checked){
                newservers+= items[i].value+",";
            }
        }
        newservers = newservers.substring(0,newservers.length-1);

        jQuery.ajax({
            type: "post",
            data: {gameproj:gameproj,mergerservers:newservers},
            url: "/mergerserver/opt",
            async:false,//false代表等待ajax执行完毕后才执行alert("ajax执行完毕")语句;
            success: function (msg) {
                if(msg == "success"){
                        window.location.href="/mergerserver/mergesvtask/list"
                        return;
                }
                alert(msg);
            }
        })
    }


     $(document).ready(function(){
           $(".checkall").click(function () {
              var check = $(this).prop("checked");
              $(".checkchild").prop("checked", check);
           });
     });

    </script>


{% endblock%}

templates/mergerserver/mergerservertask_detail.html
{% extends "index.html" %}
f
{% block body %}
    <div class="header">
        <h1 class="page-header">合服任务单详情</h1>
  	  <ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">首页</a></li>
          <li class="active">合服任务单详情</li>
          <li class="active">{{object.id}}</li>
	  </ol>
    </div>

    <div id="page-inner">

        <div >
            <table class="table table-hover table-bordered">
                    <caption>
                        任务单信息
                    </caption>
                    <thead>
                            <th>编号</th>
                            <th>创建者</th>
                            <th>项目名</th>
                            <th>创建时间</th>
                            <th>状态</th>
                            <th>状态信息</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{object.id}}</td>
                            <td>{{object.operator}}</td>
                            <td>{{object.gameproject}}</td>
                            <td>{{object.operatetime}}</td>
                            <td>{{object.get_status_display}}</td>
                            <td>{{object.execoutput}}</td>
                        </tr>
                    </tbody>
            </table>


            <table class="table table-hover table-bordered" style="width:50%">
                <caption>
                    涉及服信息
                </caption>
                <thead>
                    <th>游戏服ID</th>
                    <th>状态</th>
                    <th>状态信息</th>
                </thead>
                <tbody>
                    {% for h in serverinfo %}
                    <tr>
                        <td>{{h.0}}</td>
                        <td>{{h.1}}</td>
                        <td>{{h.2}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

templates/mergerserver/mergerservertask_list.html
{% extends "index.html" %}

{% block header %}
    <link href="/static/bootstrap/assets/js/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
{% endblock %}
{% block body %}
    <div class="header">
        <h1 class="page-header">合服任务单</h1>
  	  <ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">首页</a></li>
		  <li class="active">合服任务单</li>
	  </ol>
    </div>



    <div id="page-inner">
        <div class="table-responsive" >
            <table class="table table-hover table-bordered" id="host_table">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>项目名</th>
                    <th>创建时间</th>
                    <th>状态</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for host in object_list %}
                    <tr>
                        <td><a href="{% url 'mergerserver:mergeservertask_detail'  host.id %}">{{ host.id }}</a></td>
                        <td>{{ host.gameproject}}</td>
                        <td>{{ host.operatetime}}</td>

                        {% if host.status == 1 %}
                            <td style="color:#428bca;">{{ host.get_status_display}}</td>
                        {% elif host.status == 3 %}
                            <td style="color:#FF4500;">{{ host.get_status_display}}</td>
			            {% elif host.status == 2 %}
                            <td style="color:#DAA520;">{{ host.get_status_display}}</td>
			            {% else%}
                            <td style="color:#008000;">{{ host.get_status_display}}</td>
			            {% endif %}
 			
                        <td>
                            {% if host.status == 1 %}
                            <a href="/api/mergegame/{{host.id}}" onclick="return confirm('确认要执行此任务吗？')" data-toggle="modal" title="开服"><i class="fa fa-cloud-upload fa-lg"></i></a>&nbsp&nbsp
                            {% endif %}

                            {% if host.status == 5%}
                            <a href="/api/mergegame/{{host.id}}" onclick="return confirm('确认要执行此任务吗？')" data-toggle="modal" title="重试"><i class="fa fa-cloud-upload fa-lg"></i></a>&nbsp&nbsp
                            {% endif %}

                            {% if host.status == 2 %}
                            <a href="/api/mergegame/{{host.id}}" onclick="return confirm('确认要执行此任务吗？')" data-toggle="modal" title="重试"><i class="fa fa-cloud-upload fa-lg"></i></a>&nbsp&nbsp
                            {% endif %}
                            <a href="{% url 'openserver:openservertask_detail' host.id %}" data-toggle="modal" title="详情"><i class="fa fa-info fa-lg"></i></a>
                        </td>
                    </tr>
                {% empty %}
                    <li>暂无内容</li>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}

{% block script%}
<script src="/static/bootstrap/assets/js/dataTables/jquery.dataTables.js"></script>
<script src="/static/bootstrap/assets/js/dataTables/dataTables.bootstrap.js"></script>

    <script>
        $(document).ready(function () {
                $('#host_table').dataTable();
                $("[data-toggle='modal']").tooltip();
        });
    </script>
{% endblock %}