api/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from . import views

urlpatterns = [

    url(r'^role/nextlayer$', 'api.services.GetRoleNextLayer', name="api_rolenextlayer"),
    url(r'^getgameproj$', 'api.opensv.GetGameProject', name="api_getgameproj"),
    url(r'^getgameinfo$', 'api.opensv.GetGameInfo', name="api_getgameinfo"),

    url(r'^getmergegameinfo$', 'api.mergesv.GetMergeGameInfo', name="api_getmergegameinfo"),

    url(r'^addserverinfo$', 'api.opensv.ServerInfomationCreateApi', name="api_addserverinfo"),
    url(r'^setserverstatus$', 'api.opensv.ServerInfomationStatusApi', name="api_setserverstatus"),

    url(r'^opensv/settaskstatus$', 'api.opensv.SetServerTaskStatusApi', name="api_settaskstatus"),
    url(r'^mergesv/settaskstatus$', 'api.mergesv.SetServerTaskStatusApi', name="api_settaskstatus"),

    url(r'^getserverstatuslist$', 'api.opensv.GetServerStatusListApi', name="api_getserverstatuslist"),

    url(r'^creategame/(.+)/$', 'api.opensv.RunCreateGameApi', name="api_creategame"),
    url(r'^mergegame/(.+)/$', 'api.mergesv.RunMergeGameApi', name="api_mergegame"),

]

conf/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from  userinfo.views import login_view, logout_view, logged_view, index_view
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
urlpatterns = [
    # Examples:
    # url(r'^$', 'keeper.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', (login_required(index_view)), name='index'),
    url(r'^accounts/login/$', login_view, name='login'),
    url(r'^accounts/logout/$', logout_view, name='login_out'),
    url(r'^user/logged$', logged_view),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^userinfo/', include('userinfo.urls', namespace='userinfo')),
    url(r'^openserver/', include('openserver.urls', namespace='openserver')),
    url(r'^mergerserver/', include('mergerserver.urls', namespace='mergerserver')),
    url(r'^api/', include('api.urls', namespace='api')),

]

userinfo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^list$', login_required(views.UserListView.as_view()) ,name='user_list'),
    url(r'^profile/edit/(?P<pk>[\w-]+)$',login_required(views.UserProfileUpdate.as_view()),name='user_update'),
    url(r'^profile/detail/(?P<pk>[\w-]+)$',login_required(views.UserDetailView.as_view()),name='user_detail'),
    url(r'^profile/edit$',login_required(views.UserProfileUpdate.as_view()), name="user_edit"),
    url(r'^add$', login_required(views.UserCreateView.as_view())),
]

userinfo/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from datetime import datetime
import crypt
import random
import string
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from rest_framework import serializers


# Create your models here.


class UserManager(BaseUserManager):
    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = datetime.now()

        if not email and not username:
            raise ValueError('The given email and username must be set')

        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.username = username
        user.set_password(password)
        user.ssh_google_key = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(18))
        user.google_scratch_code = "\n".join(
            ["".join([str(x) for x in [random.randrange(0, 9) for _ in range(8)]]) for _ in range(5)])
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50,
                                unique=True, verbose_name="UserName")
    # han_name = models.CharField(max_length=10, default="", blank=True, verbose_name="中文名")
    key = models.TextField(default="", blank=True, verbose_name="Public Key")
    hash_password = models.CharField(default="", blank=True,
                                     max_length=200, verbose_name="Hash Password")
    email = models.EmailField(default="", unique=True)
    date_joined = models.DateTimeField(_('date joined'), default=datetime.now())
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    phone = models.CharField(max_length=20, verbose_name="手机号", blank=True, null=True)

    vpn_google_key = models.CharField(max_length=20, blank=True, null=True)
    ssh_google_key = models.CharField(max_length=20, blank=True, null=True)
    google_scratch_code = models.CharField(max_length=60, blank=True, null=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = "user"

    def has_perms(self, perm_list, obj=None):
        """
     Returns True if the user has each of the specified permissions. If
     object is passed, it checks if the user has all required perms for this
     object.
        """
        for perm in perm_list:
            if not self.has_perm(perm, obj):
                return False
        return True

    def save(self, *args, **kwargs):
        if self.hash_password:
            hash = crypt.crypt(self.hash_password, "$6$" + self.username + "$")
            self.hash_password = hash
        return super(User, self).save(*args, **kwargs)



    def get_absolute_url(self):
        return "/user/profile/%s" % self.username

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.username

    def __unicode__(self):
        return self.username

    def __str__(self):
        return self.username



class UserSerializer(serializers.ModelSerializer):
    def __init__(self, *args, **kwargs):
        super(UserSerializer, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ('username',)

userinfo/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
   * File Name : views.py

   * Purpose :

   * Creation Date : 15-01-2015

   * Last Modified :

   * Created By : dren
'''
import logging
from django.template import Context, loader
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import PermissionDenied
from django.views.generic.list import ListView
from django.views.generic import View
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.contrib.auth.decorators import login_required
import sys
import time
import json
import urllib
import urllib2
from requests import Request, Session
from hashlib import md5
from openserver.models import *
# from ldap3 import Server, Connection, SYNC, AUTH_SIMPLE

from .models import User
from .forms import *
logger = logging.getLogger(__name__)

class BournceBackend:
    appkey = 'bbdcd6a4191827a77fc65972'

    appid = 9
    token = 'BabelTimeToken'
    tokenUrl = 'https://bouncer.babeltime.com/token/check'
    redirect = 'http://' + settings.HOST_PORT + '/user/logged'
    userUrl = 'https://bouncer.babeltime.com/user'
    logout_url = 'https://bouncer.babeltime.com/user/logout'

    def getSign(self, request):

        if 'HTTP_X_FORWARDED_FOR' in request.META:
            ip = request.META['HTTP_X_FORWARDED_FOR']
        else:
            ip = request.META['REMOTE_ADDR']
        data = [("appid", self.appid), ("ts", int(time.time())),
                ("redirect", 'http://' + request.get_host() + '/user/logged')]
        request.session["next"] = request.GET.get('next', "")
        tmp = ''
        for d in data:
            tmp += d[0] + str(d[1])
        tmp += self.appkey
        sign = md5(tmp).hexdigest()
        data.append(("sign", sign))
        request.session["ts"] = data[1][1]
        return urllib.urlencode(data), sign

    def login(self, request):
        token = request.session.get("token", "")
        logger.info("token ssio:", token)
        if token:
            return self.isLogin(request, token)
        token = request.GET.get("BabelTimeToken", "")
        if token:
            request.session['token'] = token
        args, sign = self.getSign(request)
        goto = self.userUrl + '/login?' + args
        request.session['sign'] = sign
        # print sign, "\t", args, "\t", goto
        return HttpResponseRedirect(goto)

    def isLogin(self, request, token):
        # s = Session()
        if 'HTTP_X_FORWARDED_FOR' in request.META:
            ip = request.META['HTTP_X_FORWARDED_FOR']
        else:
            ip = request.META['REMOTE_ADDR']

        data = [("appid", self.appid),
                ("ip", ip),
                ("token", request.session["token"]),
                ("ts", int(time.time()))
                ]
        tmp = ''
        for d in data:
            tmp += d[0] + str(d[1])
        tmp += self.appkey
        logger.info(tmp, "\t", md5(tmp).hexdigest())
        sign = md5(tmp).hexdigest()
        data.append(("sign", sign))

        resp = json.loads(urllib2.urlopen(self.tokenUrl, urllib.urlencode(data)).read())
        username = resp["info"]["username"]
        logger.info(resp)
        if username:
            request.session["username"] = username
            user = self.get_or_create_user(username, "")
            user.backend = "userinfo.views.BournceBackend"
            request.user = user
            login(request, user)
            return HttpResponseRedirect(request.session.get("next", "/"))
        else:
            return HttpResponse("403")
            # pre = Request('POST', self.tokenUrl, data).prepare()
            # resp = s.send(pre)
            # return resp.text

    def logout(self,request):
        if 'HTTP_X_FORWARDED_FOR' in request.META:
            ip = request.META['HTTP_X_FORWARDED_FOR']
        else:
            ip = request.META['REMOTE_ADDR']

        data = [("appid", self.appid),
                ("ip", ip),
                ("token", request.session.get("token","")),
                ("ts", int(time.time()))
                ]
        tmp = ''
        for d in data:
            tmp += d[0] + str(d[1])
        tmp += self.appkey
        logger.info(tmp, "\t", md5(tmp).hexdigest())
        sign = md5(tmp).hexdigest()
        data.append(("sign", sign))

        resp = json.loads(urllib2.urlopen(self.logout_url, urllib.urlencode(data)).read())

        return resp

    def authenticate(self, request, token=None):
        try:
            if not request.session.get('token', ""):
                return self.login(request)
            else:
                request.user = self.get_or_create_user(username, 'bouncer')
                return self.get_or_create_user(username, 'bouncer')
        except:
            return None
            # return self.get_or_create_user(username, password)

    def get_or_create_user(self, username, password):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            info = sys.exc_info()
            logger.info(info[0], ":", info[1])
            logger.info(username)
            mail = username + '@babeltime.com'
            user = User(username=username, email=mail)
            user.is_staff = True
            user.is_superuser = False
            user.set_password('ldap a authenticated')
            user.save()
        return user

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None  # > 其中域控服务器和用户名，邮箱地址根据实际情况修改。


def logged_view(request):
    token = request.GET.get("BabelTimeToken", "")
    logger.info("token:", token)
    if token:
        request.session['token'] = token
        b = BournceBackend()
        return b.isLogin(request, token)
    else:
        return HttpResponseRedirect(request.session.get("next", "/user/list"))


def login_view(request):
    # if "192.168" not in settings.HOST_PORT and "127.0.0.1" not in settings.HOST_PORT:
    if request.method == "GET":
        request.session["next"] = request.GET.get("next", "")
        b = BournceBackend()
        return b.login(request)

    if request.method == "POST":
        username = request.POST.get('username', "")
        password = request.POST.get('password', "")
        user = authenticate(username=username, password=password)  # 校验处理
        if user is not None:  # 表示校验成功了
            login(request, user)
            if user.is_active:
                # if "frontend" in user.groups.all():
                return HttpResponseRedirect(request.session.get("next", "/user/list"))
                # else:
                #     return HttpResponseRedirect("/frontend/svn/")
            else:
                failed = "Your account has been disabled!"
                return render_to_response("login.html", {"failed": failed})
        else:
            failed = "用户名或密码错误"
            return render_to_response("login.html", {"failed": failed})
    else:
        request.session["next"] = request.GET.get("next", "")
        return render_to_response("login.html")


def logout_view(request):

    c = '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
    <html>
    <head>
    <title>Redirecting....</title>
    <body>
    You're logged out.
    </body>
    </html>'''
    #print "del seesion key:", request.session.session_key


    b = BournceBackend()
    x=b.logout(request)
    for sesskey in request.session.keys():
        logger.info("del seesion key:", sesskey)
        del request.session[sesskey]
    request.session.flush()
    logout(request)
    json.dumps(x)
    proto,rest = urllib.splittype(request.META['HTTP_REFERER'])
    res, rest = urllib.splithost(rest)
    return HttpResponseRedirect(rest)


def change_password(request):
    if request.method == 'POST':
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 == password2:
            u = User.objects.get(username__exact=request.user)
            u.set_password(password1)
            u.save()
            return HttpResponse("更改成功")
        else:
            return render_to_response('change_password.html', {"failed": "两次密码不一致", "username": request.user})
    if request.method == "GET":
        # update_session_auth_hash(request, form.user)
        return render_to_response('change_password.html', {"username": request.user})


class UserListView(ListView):
    model = User
    template_name = "userinfo/user_list.html"

    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.model.objects.all()
        return [self.request.user]

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        return context


class UserProfileUpdate(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = '/user/list'
    template_name_suffix = '_update_form'

    def get_object(self, *args, **kwargs):
        user = User.objects.get(username=self.request.user)
        if user.is_superuser and not self.slug_field:
            obj = super(UserProfileUpdate, self).get_object(*args, **kwargs)
            # if not obj == self.request.user:
            #    raise PermissionDenied
            return obj
        else:
            return user


class UserDetailView(DetailView):
    model = User


class UserCreateView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    template_name = 'userinfo/user_update_form.html'


@login_required()
def index_view(request):

    t = loader.get_template('home.html')

    task_sum=len(OpenServerTask.objects.all())

templates/userinfo/user_detail.html
{% extends "index.html" %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="/static/selfcss/selfcss.css"/>
    <script type="text/javascript" src="/static/qrcode.min.js"></script>
    <script>
        $(document).ready(function () {
            new QRCode(document.getElementById('qrcode'), "otpauth://totp/{{ object.username }}?secret={{ object.vpn_google_key }}");

        });
    </script>


{% endblock %}
{% block body %}

    <div class="header">
        <h1 class="page-header">用户信息</h1>
  	    <ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">首页</a></li>
		  <li class="active">用户信息</li>
	    </ol>
    </div>


    <div id="page-inner">


        <form action="" method="post" class="form">{% csrf_token %}

            <table width="25%" style="table-layout: fixed">
                <tr>
                    <th>编号:</th>
                    <td>{{ object.id }}</td>
                </tr>
                <tr>
                    <th>用户名:</th>
                    <td>{{ object.username }}</td>
                </tr>
                <tr>
                    <th>中文名:</th>
                    <td>{{ object.han_name }}</td>
                </tr>
                <tr>
                    <th>公钥:</th>
                    <td style="word-break:break-all">{{ object.key }}</td>
                </tr>
                <tr>
                    <th>加密后的密码:</th>
                    <td style="word-break:break-all">{{ object.hash_password }}</td>
                </tr>
                <tr>
                    <th>邮箱:</th>
                    <td>{{ object.email }}</td>
                </tr>
                <tr>
                    <th>添加时间:</th>
                    <td>{{ object.date_joined }}</td>
                </tr>
                <tr>
                    <th>激活状态:</th>
                    <td>{{ object.is_active }}</td>
                </tr>
                <tr>
                    <th>管理权限:</th>
                    <td>{{ object.is_admin }}</td>
                </tr>
                <tr>
                    <th>普通权限:</th>
                    <td>{{ object.is_staff }}</td>
                </tr>
                <tr>
                    <th>Google Auth Key</th>
                    <td>{{ object.vpn_google_key }}</td>
                </tr>

            </table>


        </form>
        <div id="qrcode"></div>

{% endblock %}

templates/userinfo/user_list.html
{% extends "index.html" %}


{% block header %}
 	<link href="/static/bootstrap/assets/js/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
    	<link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="header">
        <h1 class="page-header">账号列表</h1>
  	    <ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">首页</a></li>
		  <li class="active">账号列表</li>
	    </ol>
    </div>


    <div id="page-inner">


        <table class="table" id="user_list">
            <thead>
            <tr>
                <th>编号</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th style="width: 3.5em;"></th>
            </tr>
            </thead>
            <tbody>
            {% for user in object_list %}
                <tr>
                    <td><a href="{% url 'userinfo:user_detail' user.id %}">{{ user.id }}</a></td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <a href="{% url 'userinfo:user_update' user.id %}"><i class="fa fa-pencil"></i></a>
                        <a href="#myModal" role="button" data-toggle="modal"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% empty %}
                <li>暂无内容</li>
            {% endfor %}

            </tbody>
        </table>
{% endblock %}
{% block script %}
	<script src="/static/bootstrap/assets/js/dataTables/jquery.dataTables.js"></script>
	<script src="/static/bootstrap/assets/js/dataTables/dataTables.bootstrap.js"></script>
	<script>
	    $(document).ready(function () {
	        $('#user_list').DataTable();
	
	    });
	</script>
{%  endblock %}

templates/userinfo/user_update_form.html
{% extends "index.html" %}

{% block body %}
<script>
    function handleFiles(files) {
        if (files.length) {
            var file = files[0];
            var reader = new FileReader();
            if (/text\/\w+/.test(file.type)) {
                reader.onload = function () {
                    $("#id_key").val(this.result);
                }
                reader.readAsText(file);
            }
        }

    }
    function validate(form) {
        var ret = pass();
        return ret;
    }
    function pass() {

        var password = '', repassword = '';

        password = $('#pass1 input').val();

        repassword = $('#pass2 input').val();
        if (password === '' || repassword === '') {
            return false;
        }

        if (password.length < 6) {

            alert('密码最低由6位字符组成');
            return false;
        }
        if (password != repassword) {
            alert('输入的密码不一致');
            return false;
        }
        return true;
    }
</script>


    <div class="header">
        <h1 class="page-header">账号设置</h1>
  	    <ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">首页</a></li>
		  <li class="active">账号设置</li>
	    </ol>
    </div>




<div id="page-inner">
    <form action="" method="post" class="form" onsubmit="return validate(this);">{% csrf_token %}
        <table>
            <tr>
                <tr>
                <th>手机号:</th>
                <td id="phone">{{ form.phone }}</td>
            </tr>
                <th>公钥:</th>
                <td>{{ form.key }}<label></label></td>
                <td><a href="http://wiki.babeltime.com/pages/viewpage.action?pageId=9471364"
                       target="_blank">点击查看生成公钥方法</a></td>

            </tr>
            <tr>
                <th></th>
                <td><input type="file" id="file" onchange="handleFiles(this.files)"/></td>
            </tr>

            <tr>
                <th>输入密码:</th>
                <td id="pass1">{{ form.hash_password }}</td>
            </tr>
            <tr>
                <th>请再次输入密码:</th>
                <td id="pass2">{{ form.hash_password }}</td>
            </tr>
        </table>
        <input type="submit" value="提交"/>
    </form>
{% endblock %}